graph TD
N0["Assign x = 125 "]
N1["Assign a = -126 "]
N2["While (false) "]
N3["If (-126) "]
N4["Assign y = 1 "]
N5["Assign y = 1 "]
N6["Return (251) "]
    N0 -->|Yes| N1
    N1 -->|Yes| N2
    N2 -->|Yes| N3
    N3 -->|Yes| N4
    N4 -->|Yes| N2
    N3 -->|Yes| N5
    N5 -->|Yes| N2
    N2 -->|Yes| N6
